// user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';

// post
export const REQUEST_POST_LIST = 'REQUEST_POST_LIST';
export const RECEIVE_POST_LIST = 'RECEIVE_POST_LIST';
export const REQUEST_POST_DETAIL = 'REQUEST_POST_DETAIL';
export const RECEIVE_POST_DETAIL = 'RECEIVE_POST_DETAIL';
export const POST_VOTE_UP = 'POST_VOTE_UP';
export const POST_VOTE_DOWN = 'POST_VOTE_DOWN';

// comment
export const RECEIVE_COMMENT_LIST = 'RECEIVE_COMMENT_LIST';
export const COMMENT_MOUSEOVER = 'COMMENT_MOUSEOVER';
export const COMMENT_MOUSELEAVE = 'COMMENT_MOUSELEAVE';
export const COMMENT_SHOW_REPLY = 'COMMENT_SHOW_REPLY';
export const COMMENT_HIDE_REPLY = 'COMMENT_HIDE_REPLY';
export const COMMENT_VOTE_UP = 'COMMENT_VOTE_UP';
export const COMMENT_VOTE_DOWN = 'COMMENT_VOTE_DOWN';
export const COMMENT_DELETE = 'COMMENT_DELETE';