// user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// post
export const REQUEST_POST_LIST = 'REQUEST_POST_LIST';
export const RECEIVE_POST_LIST = 'RECEIVE_POST_LIST';
export const REQUEST_POST_DETAIL = 'REQUEST_POST_DETAIL';
export const RECEIVE_POST_DETAIL = 'RECEIVE_POST_DETAIL';
export const POST_VOTE_UP = 'POST_VOTE_UP';
export const POST_VOTE_DOWN = 'POST_VOTE_DOWN';

// comment
export const RECEIVE_COMMENT_LIST = 'RECEIVE_COMMENT_LIST';
export const COMMENT_VOTE_UP = 'COMMENT_VOTE_UP';
export const COMMENT_VOTE_DOWN = 'COMMENT_VOTE_DOWN';
export const COMMENT_DELETE = 'COMMENT_DELETE';