// user
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// post
export const REQUEST_POST_LIST = 'REQUEST_POST_LIST';
export const RECEIVE_POST_LIST = 'RECEIVE_POST_LIST';
export const REQUEST_POST_DETAIL = 'REQUEST_POST_DETAIL';
export const RECEIVE_POST_DETAIL = 'RECEIVE_POST_DETAIL';

// comment
export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST';
export const RECEIVE_COMMENT_LIST = 'RECEIVE_COMMENT_LIST';